### ISSUE TITLE
`tokenize` cannot handle extra ")"

### ISSUE THREAD

**Issue by JakeThurman** [psalaets/excel-formula-tokenizer#2]
Sample Input: 
```js
tokenize(")")
tokenize("1*1)")
tokenize("f(x))")
tokenize(") + 1")
```

Stack Trace (for any):
```
TypeError: Cannot read property 'type' of undefined
    at TokenStack.pop (.\node_modules\excel-formula-tokenizer\index.js:100:34)
    at tokenize (.\node_modules\excel-formula-tokenizer\index.js:480:32)
```

**Comment by psalaets** [comment]
You were hoping for a friendlier error? or some other result?

**Comment by JakeThurman** [comment]
My expectation was that the unmatched ) would be ignored. Not sure if this is the best option, but that was my expectation. 

The use case I am looking at was specifically for syntax highlighting as-you-type.

**Comment by psalaets** [comment]
> My expectation was that the unmatched ) would be ignored.

That's an interesting idea. This doesn't exist yet, but I could imagine some sort of "unexpected character handler" that throws an Error by default, but can be overridden to be a no-op which would handle your case.

Unfortunately, I don't have too much time nor motivation to work on this module. So if you want that feature any time soon it'll probably have to be a diy effort.
